### ISSUE TITLE
Add Sahashia

### ISSUE THREAD

**Issue by joelnitta** [joelnitta/ppg-demo#1]
Name of taxon: *Sahashia* (Botrychoideae, Ophioglossaceae, Ophioglossales)

Rank of taxon: Genus

Number of species affected: 1

Reason for change: Segregated from *Botrypus* so that the monophyly of *Botrypus* can be maintained

Reference: Zhang, Liang et al. (2020) ‘Evolutionary relationships of the ancient fern lineage the adder’s tongues (Ophioglossaceae) with description of *Sahashia* gen. nov’, Cladistics, 36(4), pp. 380–393. Available at: https://doi.org/10.1111/cla.12408.

Is this change already in [World Ferns](https://www.worldplants.de/world-ferns/ferns-and-lycophytes-list)? Yes

**Comment by joelnitta** [comment]
Since Liang et al. show that *Sahashia* renders *Botrypus* paraphyletic with high bootstrap support, I think this change should be made.

**Comment by schuettpelze** [comment]
The addition would seem to be warranted, so long as we do not want to entertain a broader circumscription of Botrychium. It would seem that Botrychium sensu Wagner (1990) is strongly supported as monophyletic.

**Comment by joelnitta** [comment]
Vote results: 110 yes 2 no; change is accepted
